GomelSat/GomelSat/Controllers/GomelSatNewsController.cs
using System.Web.Mvc;
using Services;
using Services.GomelSat;

namespace GomelSat.Controllers
{
    public class GomelSatNewsController : Controller
    {
        private readonly IGomelSatService gomelSatService;

        public GomelSatNewsController(IGomelSatService gomelSatService)
        {
            this.gomelSatService = gomelSatService;
        }

        public ActionResult Index()
        {
            var news = gomelSatService.GetNews();
            return View(news);
        }

        [HttpPost]
        public ActionResult AnalizeText(string newsHeader, string newsText)
        {
            var id = gomelSatService.SaveAnalizingText(newsHeader, newsText);
            return RedirectToAction("AnalizedData", new { id = id });
        }

        public ActionResult AnalizedData(long id)
        {
            var analizedResults = gomelSatService.GetAnalizedData(id);
            return View(analizedResults);
        }

        public ActionResult ReviewingData(long id)
        {
            var reviewingData = gomelSatService.GetReviewingData(id);
            return View(reviewingData);
        }

        [HttpPost]
        public ActionResult InsertHeaderToAnalizingText(long id, string newsHeader)
        {
            gomelSatService.UpdateAnalizingDataHeader(id, newsHeader);
            return RedirectToAction("ReviewingData", new { id = id });
        }

        [HttpPost]
        public ActionResult InsertImageLinkToAnalizingText(long id, string imageLink)
        {
            gomelSatService.UpdateAnalizingDataImageLink(id, imageLink);
            return RedirectToAction("ReviewingData", new { id = id });
        }

        [HttpPost]
        public ActionResult InsertSourceLinkToAnalizingText(long id, string sourceLink)
        {
            gomelSatService.UpdateAnalizingDataSourceLink(id, sourceLink);
            return RedirectToAction("ReviewingData", new { id = id });
        }

        [HttpPost]
        public ActionResult OpenGomelSatNewsRedactor(string header, string shortText, string text)
        {
            gomelSatService.OpenGomelSatRedactor(header, shortText, text);
            return RedirectToAction("Index", "GomelSatNews");
        }

        [HttpPost]
        public ActionResult OpenImageDownloader(long id)
        {
            var link = gomelSatService.GetImageLink();
            gomelSatService.UpdateAnalizingDataImageLink(id, link);
            return RedirectToAction("ReviewingData", new { id = id });
        }
    }
}

GomelSat/GomelSat/Controllers/GomelSatSettingsController.cs
using System.Collections.Generic;
using System.Web.Mvc;
using FilesManagers.Constants;
using Services.GomelSat;
using Services.Words;

namespace GomelSat.Controllers
{
    public class GomelSatSettingsController : Controller
    {
        private readonly IGomelSatService gomelSatService;

        public GomelSatSettingsController(IGomelSatService gomelSatService)
        {
            this.gomelSatService = gomelSatService;
        }

        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult RefreshNews()
        {
            gomelSatService.RefreshNews();
            return RedirectToAction("Index", "GomelSatNews");
        }
    }
}

GomelSat/GomelSat/Controllers/GomelSatSiteLinkController.cs
using System.Web.Mvc;
using Services.GomelSat;

namespace GomelSat.Controllers
{
    public class GomelSatSiteLinkController : Controller
    {
        private IGomelSatService gomelSatService;

        public GomelSatSiteLinkController(IGomelSatService gomelSatService)
        {
            this.gomelSatService = gomelSatService;
        }

        // GET: GomelSatSiteLink
        public ActionResult Index()
        {
            return View();
        }

        public PartialViewResult Links()
        {
            var links = gomelSatService.GetGomelSatSiteLinks();
            return PartialView(links);
        }
    }
}

GomelSat/GomelSat/Controllers/WordsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using FilesManagers.Constants;
using Services.Words;

namespace GomelSat.Controllers
{
    public class WordsController : Controller
    {
        private readonly IWordService wordService;

        public WordsController(IWordService wordService)
        {
            this.wordService = wordService;
        }

        // GET: Words
        public ActionResult Index()
        {
            var wordsToDelete = wordService.GetWordListToDelete();
            return View(wordsToDelete);
        }

        [HttpPost]
        public ActionResult AddWord(string word)
        {
            wordService.AddWord(word);
            return RedirectToAction("Index");
        }

        public ActionResult RemoveWords(IEnumerable<string> words)
        {
            wordService.DeleteWords(words);
            return RedirectToAction("Index");
        }

        public ActionResult DownloadWords()
        {
            var file = wordService.GetWordsFile();
            return File(file, "text/plain", FileNameConstants.WordsFileName);
        }

        [HttpPost]
        public ActionResult QuickAddWord(string word, int analizedTextId)
        {
            wordService.AddWord(word);
            return RedirectToAction("AnalizedData", "GomelSatNews", new { id = analizedTextId });
        }
    }
}

GomelSat/GomelSat/Views/GomelSatNews/AnalizedData.cshtml
@{
    ViewBag.Title = "AnalizedData";
}

@model Services.GomelSat.Models.AnalizedDataViewModel

@section scripts
{
    <script type="text/javascript">
        window.onload = function () {

            $(".add-word-window").hide();

            $(".underlined-word").click(function (event) {

                var element = event.toElement;
                var text = element.innerText.trim();

                var x = event.pageX;
                var y = event.pageY;

                console.log(event);

                $(".add-word-window").css({ top: y, left: x, position: 'absolute' });
                
                $(".add-word-window-word-text").text(text);
                $(".add-word-window-word-text-value").val(text);

                $(".add-word-window").show();
            });
        }

        function modalCancel() {
            $(".add-word-window").hide();
        }
    </script>
}

@{
    var index = 0;
}

@{Html.RenderAction("Links", "GomelSatSiteLink");}

@foreach (var header in @Model.AnalizedTextModels)
{
    index++;
    <div class="page-header">
        <h2> @Html.Raw(@header.NewsHeader) </h2>
        <p>
            @Html.Raw(@header.NewsText)
        </p>
    </div>
}

<div class="following-box panel panel-primary following-box-with-scroll">
    <div class="following-box-content following-box-with-scroll">
        <h4><b>@Model.HeaderText</b></h4>

        <div class="go-to-review-button">
            <a class="btn btn-primary go-to-review-button" href="@Url.Action("ReviewingData", "GomelSatNews", new { id = @Model.Id })">Go to review</a>
        </div>

        <br/>
        <br/>

        @Model.ContentText
    </div>
</div>

<div class="add-word-window">
    <div class="add-word-window-word-full-text">
        Are you sure you want to add word <span class="add-word-window-word-text"> </span> to ban list?
    </div>
    <div>
        <input type="button" class="btn btn-primary pull-left" onclick="modalCancel()" value="Cancel">
        @using (Html.BeginForm("QuickAddWord", "Words", new { analizedTextId = @Model.Id }, FormMethod.Post, new { }))
        {
            <div>
                <input type="hidden" name="word" value="" class="add-word-window-word-text-value" />
                <input type="submit" class="btn btn-primary pull-right" value="Confirm">
            </div>
        }
    </div>
</div>

GomelSat/GomelSat/Views/GomelSatNews/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

@model IEnumerable<DataParsers.Models.GomelSatNewsModel>

@section Scripts{
    <script type="text/javascript">
        function RemoveAnnoyingWords(id) {
            setTimeout(function () {

                var oldValue = $('#' + id).val();
                var newValue = oldValue.replace(/Взято с http:\/\/www.telesat-news.net.*Спутниковые и Транспондерные ТелеНовости$/, "");
                $('#' + id).val(newValue);

            }, 100);
        }
    </script>
}

@{Html.RenderAction("Links", "GomelSatSiteLink");}

@{
    var index = 0;
}

@foreach (var header in @Model)
{
    index++;
    <div class="page-header">
        <h2> @Html.Raw(@header.HeaderName) </h2>
        <p>
            @Html.Raw(@header.HeaderText)
        </p>

        <br/>

        <button class="btn btn-primary pull-right" type="button" data-toggle="collapse" data-target=@("#collapseText" + index) aria-expanded="false" aria-controls="collapseText">
            Show/Hide full text of this article
        </button>

        <br/>

        <div class="collapse" id=@("collapseText" + index)>
            <div class="well">
                @Html.Raw(@header.Text)
            </div>
        </div>
    </div>
}

<div class="following-box panel panel-primary ">
    <div class="panel-heading">
        <h3 class="panel-title">Please check the text</h3>
    </div>
    <div class="following-box-content">
        @using (Html.BeginForm("AnalizeText", "GomelSatNews", new {}, FormMethod.Post, new {}))
        {
            <p> Please, write the headline here: </p>

            <input type="text" id="newsHeader" name="newsHeader" class="following-box-header" onpaste="RemoveAnnoyingWords('newsHeader')"/>

            <p> Please, write the text here: </p>

            <textarea id="newsText" name="newsText" class="following-box-text" onpaste="RemoveAnnoyingWords('newsText')"></textarea>

            <input type="submit" class="btn btn-primary pull-right" value="Search">
        }
    </div>
</div>

GomelSat/GomelSat/Views/GomelSatNews/ReviewingData.cshtml
@{
    ViewBag.Title = "ReviewingData";
}

@model Services.GomelSat.Models.ReviewingDataViewModel

@section scripts
{
    <script type="text/javascript">

        var titleExists = '@Model.TitleExists' === 'True';
        var imageLinkExists = '@Model.ImageExists' === 'True';
        var sourceLinkExists = '@Model.LinkExists' === 'True';

        function RemoveAnnoyingWords(id) {
            setTimeout(function () {

                var oldValue = $('#' + id).val();
                var newValue = oldValue.replace(/Взято с http:\/\/www.telesat-news.net.*Спутниковые и Транспондерные ТелеНовости$/, "");
                $('#' + id).val(newValue);

            }, 100);
        }

        function ShowModals() {
            if (!titleExists) {
                $("#headerModalButton").click();
                return;
            }

            if (!imageLinkExists) {
                $("#imageModalButton").click();
                return;
            }

            if (!sourceLinkExists) {
                $("#sourceLinkModalButton").click();
                return;
            }
        }

        ShowModals();
    </script>
}


<button id="headerModalButton" type="button" data-toggle="modal" data-target="#headerModal" hidden>Open Modal</button>

<div class="container">
    <!-- Modal -->
    <div class="modal fade" id="headerModal" role="dialog">
        <div class="modal-dialog">

            <!-- Modal content-->
            <div class="modal-content ">
                <div class="modal-header dialog-box-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">Information</h4>
                </div>

                <div class="modal-body dialog-box-content">
                    <div class="text-center">
                        <h4 class="alert-info alert">
                            Please, enter <b>headline of the article</b> before starting of review.
                        </h4>
                    </div>

                    <div class="form-group">
                        @using (Html.BeginForm("InsertHeaderToAnalizingText", "GomelSatNews", new {Id = @Model.Id}, FormMethod.Post, new {}))
                        {
                            <input type="text" id="newsHeader" name="newsHeader" class="dialog-input" onpaste="RemoveAnnoyingWords('newsHeader')"/>

                            <div class="modal-footer">
                                <button type="submit" class="btn btn-primary">Enter</button>
                            </div>
                        }
                    </div>

                </div>
            </div>

        </div>
    </div>
</div>

<button id="imageModalButton" type="button" data-toggle="modal" data-target="#imageModal" hidden>Open Modal</button>

<div class="container">
    <!-- Modal -->
    <div class="modal fade" id="imageModal" role="dialog">
        <div class="modal-dialog">

            <!-- Modal content-->
            <div class="modal-content ">
                <div class="modal-header dialog-box-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">Information</h4>
                </div>

                <div class="modal-body dialog-box-content">
                    <div class="text-center">
                        <h4 class="alert-info alert">
                            Please, click <b>Start uploading image</b>
                        </h4>
                    </div>

                    <div class="form-group">
                        @using (Html.BeginForm("OpenImageDownloader", "GomelSatNews", new { Id = @Model.Id }, FormMethod.Post, new { }))
                        {
                            <div class="modal-footer">
                                <button type="submit" class="btn btn-primary">Start uploading image</button>
                            </div>
                        }
                    </div>

                </div>
            </div>

        </div>
    </div>
</div>

<button id="sourceLinkModalButton" type="button" data-toggle="modal" data-target="#sourceLinkModal" hidden>Open Modal</button>

<div class="container">
    <!-- Modal -->
    <div class="modal fade" id="sourceLinkModal" role="dialog">
        <div class="modal-dialog">

            <!-- Modal content-->
            <div class="modal-content ">
                <div class="modal-header dialog-box-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">Information</h4>
                </div>

                <div class="modal-body dialog-box-content">
                    <div class="text-center">
                        <h4 class="alert-info alert">
                            Please, enter <b>source link</b> (formatted or not) here before starting of review.
                        </h4>
                    </div>

                    <div class="form-group">
                        @using (Html.BeginForm("InsertSourceLinkToAnalizingText", "GomelSatNews", new { Id = @Model.Id }, FormMethod.Post, new { }))
                        {
                            <input type="text" id="sourceLink" name="sourceLink" class="dialog-input" />

                            <div class="modal-footer">
                                <button type="submit" class="btn btn-primary">Enter</button>
                            </div>
                        }
                    </div>

                </div>
            </div>

        </div>
    </div>
</div>

<div>
    @using (Html.BeginForm("OpenGomelSatNewsRedactor", "GomelSatNews", new {Id = @Model.Id}, FormMethod.Post, new {}))
    {
        <h3 class="news-text-header">Headline</h3>
        <input type="text" value="@Model.Title" class="header-text" name="header"/>

        <h3 class="news-text-header">Short Text</h3>
        <textarea class="shot-text-area" name="shortText">@Model.ShortText</textarea>

        <h3 class="news-text-header">Text</h3>
        <textarea class="long-text-area" name="text">@Model.Text</textarea>

        <br/>
        <br/>
        
        <div>
            <button type="submit" href="@Url.Action("OpenGomelSatNewsRedactor", "GomelSatNews", new {id = @Model.Id})" class="btn btn-primary">Add new article</button>
        </div>
    }

</div>

GomelSat/GomelSat/Views/GomelSatSettings/Index.cshtml
@{
    ViewBag.Title = "Index";
}

@model Services.Words.Models.WordListToDeleteViewModel

<div class="panel panel-primary settings-panel">
    <div class="panel-heading">
        <h3 class="panel-title">Data settings</h3>
    </div>
    <div class="settings-content">
        <div class="text-center">
            <h4 class="alert-info alert">
                Please, if you need to refresh some news, click this button <br />
                (<b>Warning!</b> Please, don't use this functionality more than once in 10 minutes)
            </h4>
        </div>
        @using (Html.BeginForm("RefreshNews", "GomelSatSettings", new { }, FormMethod.Post, new { }))
        {
            <div>
                <input type="submit" class="btn btn-primary pull-left settings-action-button" value="Refresh news">
            </div>
        }

        <div class="modal-end-line">
            Text
        </div>

    </div>
</div>

GomelSat/GomelSat/Views/GomelSatSiteLink/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

GomelSat/GomelSat/Views/GomelSatSiteLink/Links.cshtml
@{
    ViewBag.Title = "Links";
}

@model IEnumerable<Services.GomelSat.Models.SiteLinkViewModel>

<div class="gomel-sat-list-links panel panel-primary">
    <div class="panel-heading">
        <h3 class="panel-title">Links</h3>
    </div>
    <div class="following-box-content">
        <ul class="nav nav-pills nav-stacked">
            @foreach (var item in Model)
            {
                <li>
                    <a href="@item.Link" target="_blank">@item.Name</a>
                </li>
            }
        </ul>
    </div>
</div>

GomelSat/GomelSat/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top navbar-line">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @*@Html.ActionLink("Application Gomel-Sat Helper", "Index", "GomelSatNews", new { area = "" }, new { @class = "navbar-brand" })*@
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            Gomel-Sat
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li class="nav-dropdown-button">@Html.ActionLink("Gomel-Sat", "Index", "GomelSatNews")</li>
                            <li class="nav-dropdown-button">@Html.ActionLink("Gomel-Sat Settings", "Index", "GomelSatSettings")</li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            Words
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li class="nav-dropdown-button">@Html.ActionLink("Word Settings", "Index", "Words")</li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        <a href="#" class="back-to-top">Back to Top</a>

        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

GomelSat/GomelSat/Views/Words/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<div class="panel panel-primary settings-panel">
    <div class="panel-heading">
        <h3 class="panel-title">Word settings</h3>
    </div>
    <div class="settings-content">
        <div class="text-center">
            <h4 class="alert-info alert">
                Please, write the word you want to add to exception list <br />
            </h4>
        </div>
        @using (Html.BeginForm("AddWord", "Words", new { }, FormMethod.Post, new { }))
        {
            <div class="input-group-lg word-text-input-wrapper">
                <h4 class="text-left text-info">Word:</h4>
                <input type="text" name="word" id="word" class="form-control word-input">
            </div>

            <div>
                <input type="submit" class="btn btn-primary pull-left settings-action-button" value="Add word">
            </div>
        }

        <div class="modal-end-line">
            Text
        </div>

        @using (Html.BeginForm("RemoveWords", "Words", new { }, FormMethod.Post, new { }))
        {
            <div class="word-list-row">
                @foreach (var nextWord in Model.Words)
                {
                    <div class="form-control word-list-inside-row">
                        <input id="@nextWord" name="words" type="checkbox" value="@nextWord"> @nextWord
                    </div>
                }
            </div>

            <div>
                <input type="submit" class="btn btn-primary pull-left settings-action-button" value="Remove words" />
            </div>
        }

        <div class="modal-end-line">
            Text
        </div>

        <div class="text-center">
            <h4 class="alert-info alert">
                If you want to download list of words, please, click here: <br />
            </h4>
        </div>
        <div>
            <a href='@Url.Action("DownloadWords", "Words", new { })' class="btn btn-primary pull-left settings-action-button"> Download list of words </a>
        </div>

        <div class="modal-end-line">
            Text
        </div>

    </div>
</div>